apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: python:3.7
          command: ["python", "-m", "http.server", "8080"]
          ports:
            - containerPort: 8080